global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'deploylens-backend'
    static_configs:
      - targets: ['deploylens-backend:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8090']
    metrics_path: '/prometheus'
